version: "3"

services:
  mysql:
    image: mysql:8.0
    container_name: bambu-db
    environment:
      - MYSQL_DATABASE=bambu
      - MYSQL_ROOT_PASSWORD=123456
    ports:
      - "3306:3306"
    command: ["--character-set-server=utf8mb4", "--collation-server=utf8mb4_unicode_ci"]
    volumes:
      - ./db:/docker-entrypoint-initdb.d

  redis:
    image: redis:latest
    container_name: redis
    ports:
      - "6379:6379"

  celery:
    build:
      context: .
    container_name: celery
    command: bash ../scripts/run_celery.sh
    depends_on:
      - redis
    links:
      - redis

  web:
    container_name: web
    command: bash ../scripts/run_webserver.sh
    build: .
    ports:
      - "5000:5000"
    depends_on:
      - redis
      - mysql
    links:
      - redis
      - mysql