# PUBMED
pubmed_filters = [["Abstract", "Free full text", "Full text"],
               ["Books and documents", "Clinical trial", "Meta-Analysis", "Randomized Controlled Trial", "Review", "Systematic Review"],
               ["Humans", "Other Animals", "Male", "Female"],
               ["English", "Portuguese", "Spanish"],
               ["Associated data", "Exclude preprints", "MEDLINE"]
               ]
    

pubmed_dict = {
        "Abstract": 'fha', 
        "Free full text": 'ffrft', 
        "Full text": 'fft',
        "Books and documents": 'pubt.booksdocs', 
        "Clinical trial": 'pubt.clinicaltrial',
        "Meta-Analysis": 'pubt.meta-analysis',
        "Randomized Controlled Trial": 'pubt.randomizedcontrolledtrial',
        "Review": 'pubt.review',
        "Systematic Review": 'pubt.systematicreview',

        "Humans": 'hum_ani.humans',
        "Other Animals": 'hum_ani.animal',
        "Male": 'sex.male',
        "Female": 'sex.female',

        "English": 'lang.english',
        "Portuguese": 'lang.portuguese',
        "Spanish": 'lang.spanish',

        "Associated data": 'articleattr.data', 
        "Exclude preprints": 'other.excludepreprints',
        "MEDLINE": 'other.medline'
        }


# SCOPUS
scopus_dict = {
        # FIELD RESTRICTION
        'All fields': 'ALL',
        'Abstract': 'ABS',
        'Affiliation ID': 'AF-ID',
        'Affiliation': 'AFFIL',
        'Affiliation city': 'AFFILCITY',
        'Affiliation country': 'AFFILCOUNTRY',
        'Affiliation organization': 'AFFILORG',
        'Article number': 'ARTNUM',
        'Author identifier Number': 'AU-ID',
        'Author name': 'AUTHOR-NAME',
        'Author': 'AUTH',
        'Author first initial': 'AUTHFIRST',
        'Author last name': 'AUTHLASTNAME',
        'Collaboration author': 'AUTHCOLLAB',
        'Author keywords': 'AUTHKEY',
        'CAS registry number': 'CASREGNUMBER',
        'Chemical': 'CHEM',
        'Chemical name': 'CHEMNAME',
        'Code': 'CODEN',
        'Conference information': 'CONF',
        'Conference location': 'CONFLOC',
        'Conference name': 'CONFNAME',
        'Conference sponsors': 'CONFSPONSORS',
        'Document type': 'DOCTYPE',
        'Publication stage': 'PUBSTAGE',
        'DOI': 'DOI',
        'Editor first name': 'EDFIRST',
        'Editor': 'EDITOR',
        'Editor last name': 'EDLASTNAME',
        'EISSN': 'EISSN',
        'Exact source title': 'EXACTSRCTITLE',
        'First author': 'FIRSTAUTH',
        'Funding sponsor': 'FUND-SPONSOR',
        'Funding sponsor acronym': 'FUND-ACR',
        'Funding grant number': 'FUND-NO',
        'Index terms': 'INDEXTERMS',
        'ISBN': 'ISBN',
        'ISSN': 'ISSN',
        'ISSNP': 'ISSNP',
        'Issue': 'ISSUE',
        'Keywords': 'KEY',
        'Language': 'LANGUAGE',
        'Manufacturer': 'MANUFACTURER',
        'Open access': 'OPENACCESS',
        'First page': 'PAGEFIRST',
        'Last page': 'PAGELAST',
        'Pages': 'PAGES',
        'PubMed identifier': 'PMID',
        'Publisher': 'PUBLISHER',
        'Year of publication': 'PUBYEAR',
        'References': 'REF',
        'Reference authors': 'REFAUTH',
        'Reference title': 'REFTITLE',
        'Reference source title': 'REFSRCTITLE',
        'Reference publication year': 'REFPUBYEAR',
        'Reference article number': 'REFARTNUM',
        'Reference page numbers': 'REFPAGE',
        'Reference first page': 'REFPAGEFIRST',
        'Sequence bank': 'SEQBANK',
        'Sequence number': 'SEQNUMBER',
        'Source title': 'SRCTITLE',
        'Source type': 'SRCTYPE',
        'Subject area': 'SUBJAREA',
        'Title': 'TITLE',
        'Title/Abstract': 'TITLE-ABS-KEY',
        'Title/Abstract/Keyword/Author': 'TITLE-ABS-KEY-AUTH',
        'Tradename': 'TRADENAME',
        'Volume': 'VOLUME',
        'Website': 'WEBSITE',
        }

scopus_doctype = {
        # DOCTYPE
        'Article': 'ar',
        'Abstract report': 'ab',
        'Book': 'bk',
        'Business article': 'bz',
        'Book chapter': 'ch',
        'Conference paper': 'cp',
        'Conference review': 'cr',
        'Editorial': 'ed',
        'Erratum': 'er',
        'Letter': 'le',
        'Note': 'no',
        'Press release': 'pr',
        'Review': 're',
        'Short survey': 'sh',

        # PUBSTAGE
        'Article in press': 'aip',
        'Final document': 'final',
        }

scopus_srctype = {
        # SRCTYPE
        'Journal': 'j',
        'Book': 'b',
        'Book series': 'k',
        'Conference proceeding': 'p',
        'Report': 'r',
        'Trade publication': 'd',
        }

scopus_subjarea = {
        # SUBJAREA
        'Agricultural and biological sciences': 'AGRI',
        'Arts and humanities': 'ARTS',
        'Biochemistry, genetics and molecular Biology': 'BIOC',
        'Business, management and accounting': 'BUSI',
        'Chemical engineering': 'CENG',
        'Chemistry': 'CHEM',
        'Computer science': 'COMP',
        'Decision sciences': 'DECI',
        'Dentistry': 'DENT',
        'Earth and planetary sciences': 'EART',
        'Economics, econometrics and finance': 'ECON',
        'Energy': 'ENER',
        'Engineering': 'ENGI',
        'Environmental science': 'ENVI',
        'Health professions': 'HEAL',
        'Immunology and microbiology': 'IMMU',
        'Materials science': 'MATE',
        'Mathematics': 'MATH',
        'Medicine': 'MEDI',
        'Neuroscience': 'NEUR',
        'Nursing': 'NURS',
        'Pharmacology, toxicology and pharmaceutics': 'PHAR',
        'Physics and astronomy': 'PHYS',
        'Psychology': 'PSYC',
        'Social sciences': 'SOCI',
        'Veterinary': 'VETE',
        'Multidisciplinary': 'MULT'                        
        }
        